name: cloud_power_salesman

description: Production Ready Salesman App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # ROUTING
  go_router: ^15.1.2

  # FIREBASE
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5

  # LOCAL DATABASE
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # UTILITIES
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  uuid: ^4.5.1

  # JSON / MODELS
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # UI
  gap: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # CODE GENERATION
  build_runner: 2.4.6
  freezed: 2.4.7
  json_serializable: 6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf

  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500

  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600

  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700