// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWmWYvsHDwKbeMuoVMvGgS4sykMOr9KI',
    appId: '1:494756589888:web:784560b3db2ced7d5e0aa5',
    messagingSenderId: '494756589888',
    projectId: 'cloud-backend-f0281',
    authDomain: 'cloud-backend-f0281.firebaseapp.com',
    storageBucket: 'cloud-backend-f0281.firebasestorage.app',
    measurementId: 'G-3FRF17YN8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3M42B2YQYWvF5YXPaVsRMh3nKKe8YG-o',
    appId: '1:494756589888:android:aa9abf3b6686acb95e0aa5',
    messagingSenderId: '494756589888',
    projectId: 'cloud-backend-f0281',
    storageBucket: 'cloud-backend-f0281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7i_KVCVmQs2crYaxVIEKgrlAoAyo0k9Y',
    appId: '1:494756589888:ios:b59ffaf58968b86b5e0aa5',
    messagingSenderId: '494756589888',
    projectId: 'cloud-backend-f0281',
    storageBucket: 'cloud-backend-f0281.firebasestorage.app',
    iosBundleId: 'com.cloudpower.salesman',
  );

}